version: '3.5'

services:
  post_db:
    container_name: post_db
    image: postgres
    ports:
      - "54323:5432"
    volumes:
      - post_db:/var/lib/postgresql
    environment:
      POSTGRES_DB: post
      POSTGRES_PASSWORD: post_54321
    networks:
      - post_network
    restart: unless-stopped

 
  


networks:
  post_network:
    driver: bridge

volumes:
  post_db: {}
  # minio_storage: {}

