version: '3.5'

services:
  post:  # New service
    container_name: post
    build:
      context: .
    ports:
      - "8090:8090"
    networks:
      - auth-service_social_media_network
    restart: unless-stopped
    env_file:
      - base.env
 
  


networks:
  auth-service_social_media_network:
    external:
      name: auth-service_social_media_network  # Define the network as external

