version: '3.5'

services:
  post_db:
    container_name: post_db
    image: postgres
    ports:
      - "54323:5432"
    volumes:
      - post_db:/var/lib/postgresql
    environment:
      POSTGRES_DB: post
      POSTGRES_PASSWORD: post_54321
    networks:
      - social_media_network
    restart: unless-stopped

  social_media_redis:
    container_name: social_media_redis
    image: 'redis:7-alpine'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=6379
    networks:
        - social_media_network
    ports:
      - '63792:6379'
 
  


networks:
  social_media_network:
    driver: bridge

volumes:
  post_db: {}
  # minio_storage: {}

